### ISSUE TITLE
CI and codecov setup

### ISSUE THREAD

**Issue by layik** [layik/geocoder#1]

**Comment by Robinlovelace** [comment]
Options that can automate this include https://usethis.r-lib.org/reference/github_actions.html and https://docs.ropensci.org/tic/reference/use_tic.html

**Comment by layik** [comment]
Looks like `use_github_action` is not just a line :) Might be better doing it manually this time, it is not the CRAN function to be clear. I love `usethis`. I might try `tic` later.

**Comment by Robinlovelace** [comment]
Great. If in the process you figure out how to get sf dependencies working on GH actions, please let us know!

Relevant .travis.yml code: https://github.com/ITSLeeds/geofabrik/blob/master/.travis.yml#L12-L18


Relevant (failing) .ghactions code - see https://github.com/r-lib/usethis/issues/1005 for context: https://github.com/ropensci/stplanr/blob/master/.github/workflows/R-CMD-check.yaml

Heads-up @jimhester and @pat-s who may be interested in this from `tic` and `usethis` perspectives (thanks for awesome CI packages!).

**Comment by pat-s** [comment]
We do not yet have official support for GH actions in {tic} but you can have a sneak preview [here](https://github.com/ropenscilabs/tic.package/blob/107faf996234d3a9b0808293b8a40f3b6d4684bc/.github/workflows/main.yml). 

`sysreqs` only works reliably for Linux atm and even there its kinda outdated atm (already talked to @gaborcsardi to help maintaining).

Just install spatial system deps via `brew`. But be aware that the `osgeo4mac` tap is also not really robust but there is no alternative (You get `gdal`,  `proj` (v6!) and `geos` from the core brew tap though).

See [here](https://github.com/mlr-org/mlr/blob/96796e0c6c24170ee36572e3dbfba3ff49f32c88/.github/workflows/main.yml#L121-L125) for some GH actions tries for spatial libs on macOS.

Though atm I'd still recommened to use Travis/Circle for semi-complicated CI setups until GH Actions is more mature.

**Comment by Robinlovelace** [comment]
Many thanks for the detailed reply Pat, really useful.

**Comment by layik** [comment]
Really useful stuff @Robinlovelace and @pat-s. I am sure GH will learn from Travis and Circle quickly.

**Comment by pat-s** [comment]
There's not really anything to learn in that sense, its just that people using GH actions always want to build on all platforms and this comes with some pain. Simply because it means that people need to be familiar with installing system deps on three operating systems (even though the binaries on Windows work really good).

On Travis most people just build on Linux and might even be unaware of the macOS option (in my experience).

This is when `sysreqs` comes into place which should do all of this for you in the background, scraping the relevant information from a pkgs DESCRIPTION file.

Installation trouble of a spatial stack on macOS does not differ between CI providers. The troubles for a robust spatial stack on macOS is a thing unrelated to CI systems.

**Comment by layik** [comment]
Thanks @pat-s. GH actions are very young and I think it (GH devs) will catchup with Travis but right now I could not find any ref to R package. So, for now I will rely on Travis + Codecov to do "the job".

@Robinlovelace thanks for the `geofabrik` link, `stats19` remains the gold standard.

Various commits.

**Comment by layik** [comment]
@Robinlovelace [see](https://github.com/layik/geocoder/blob/428a4f4befd7566da876cd17fe507366373c65a7/.travis.yml#L23) how easy it is to run a docker during build and run tests.

**Comment by Robinlovelace** [comment]
> @Robinlovelace see how easy it is to run a docker during build and run tests.

Seriously impressive. Can Travis build off a docker container though? Amazing that a few lines of code give you a full Docker container to interact with.

**Comment by layik** [comment]
Sure and push it anywhere.

**Comment by layik** [comment]
So far, my understanding of Actions for an R package build, having reviewed [all](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners) Ubuntu, Win and MacOS is that there is no R installed on any of them. 

Therefore, and until then, someone like Hadley would have to write a bash such as [this](https://github.com/JasonEtco/upload-to-release?files=1). Then we all go: use Hadley's build script. 

I could have a go at writing one @Robinlovelace. 

That is what I mean by GH will learn from or catch-up with Travis.

**Comment by pat-s** [comment]
All there already.

https://github.com/r-lib/actions

https://resources.rstudio.com/rstudio-conf-2020/azure-pipelines-and-github-actions-jim-hester

**Comment by layik** [comment]
@pat-s thanks for letting me know. Both Google and Github in my case, were not up to date with these efforts of Jim and others. First commit on that repo is 10th Oct 2019 and it is such an understatement to say "some pain" compared to `language: r` of [Travis](https://docs.travis-ci.com/user/languages/r/).

Moving on...the [examples](https://github.com/r-lib/actions/tree/master/examples), I think, would take months to be "painless". Nevertheless, I spent the morning learning about Actions so I think I am in a position to test them on a sample project I just built with a basic BUILD and CHECK commands.

It is great to do things all in Github.

**Comment by pat-s** [comment]
Not sure if I would recommend GH Actions for people just getting started with CI.

I'd rather point you to Travis CI via

```r
remotes::install_github("ropensci/tic")
tic::use_tic()
```

There is also some setup work involved there but its way more mature already.
